/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticketgb;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Ryan
 */
public class main extends javax.swing.JFrame {
String nol_jam = "";
String nol_menit = "";
String nol_detik = "";
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbjk = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btncetak = new javax.swing.JButton();
        txtharga = new javax.swing.JTextField();
        txttelp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Jam = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 51));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Jenis Kelamin :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 60, 90, 20);

        cbjk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Pilih Salah Satu ---", "Laki - Laki", "Wanita" }));
        cbjk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjkActionPerformed(evt);
            }
        });
        jPanel1.add(cbjk);
        cbjk.setBounds(100, 80, 190, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("No Telp(dapat dihubungi) :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 110, 170, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Harga :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 160, 70, 20);

        txtnama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtnama);
        txtnama.setBounds(100, 30, 190, 30);

        jButton1.setText("jButton1");
        jPanel1.add(jButton1);
        jButton1.setBounds(110, 260, 190, 23);

        btncetak.setText("CETAK");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });
        jPanel1.add(btncetak);
        btncetak.setBounds(100, 220, 190, 23);

        txtharga.setEditable(false);
        txtharga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtharga.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtharga.setText("7000");
        jPanel1.add(txtharga);
        txtharga.setBounds(100, 180, 190, 30);

        txttelp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txttelp);
        txttelp.setBounds(100, 130, 190, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Nama :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(100, 10, 40, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 70, 390, 260);

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mohon isi data dengan data asli ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(100, 20, 220, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("demi keamanan anda dan kemudahan kami");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(70, 40, 270, 20);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("Masukkan Data Diri");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(100, -10, 180, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 390, 70);

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));
        jPanel3.setLayout(null);

        jButton3.setText("jButton3");
        jPanel3.add(jButton3);
        jButton3.setBounds(240, 230, 73, 23);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Sugeng Rawuh Ing ArgoTuli");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(80, 0, 240, 40);

        Jam.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Jam.setText("xx-xx-xx");
        jPanel3.add(Jam);
        Jam.setBounds(270, 30, 100, 30);

        tanggal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tanggal.setText("xx-xx-xxxx");
        jPanel3.add(tanggal);
        tanggal.setBounds(130, 30, 80, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Tanggal :");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(70, 30, 70, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Pukul :");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(220, 30, 70, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 330, 390, 70);

        setSize(new java.awt.Dimension(407, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
    String tgl1 = tanggal.getText();
    String jam1 = Jam.getText();
    String SQL = "INSERT INTO tb_transaksi (no_pelanggan,nama,jenkel,no_telp,tanggal,jam,harga) VALUES"
            + "("+null+",'"+txtnama.getText()+"','"+cbjk.getSelectedItem()+"',"+txttelp.getText()+","
            + "'"+tgl1+"','"+jam1+"',"+txtharga.getText()+");";
    

    int status = db_koneksi.execute(SQL);
    if (status == 1){
        JOptionPane.showMessageDialog(this, "Data berhasil diproses", "Berhasil "
                + ",We did it", JOptionPane.INFORMATION_MESSAGE);
        String nama = txtnama.getText();
        String jenkel = cbjk.getSelectedItem().toString();
        String telp = txttelp.getText();
        new tiket(nama,jenkel,telp,tgl1,jam1).show();
        this.dispose();
    }else{
        JOptionPane.showMessageDialog(this, "Data gagal diproses, mohon cek data anda",
                "Coba Lengkapi data diatas! :*", JOptionPane.WARNING_MESSAGE);
        }
    
    
    
   
    
    txtnama.setText("");
    cbjk.setSelectedItem("--- Pilih Salah Satu ---");
    txttelp.setText("");
    
    
    
    }//GEN-LAST:event_btncetakActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    SetJam();
    setTanggal();
    }//GEN-LAST:event_formWindowOpened

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void cbjkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbjkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jam;
    private javax.swing.JButton btncetak;
    private javax.swing.JComboBox cbjk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel tanggal;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttelp;
    // End of variables declaration//GEN-END:variables

     public void setTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new
        java.text.SimpleDateFormat("dd/MM/yyyy");
        tanggal.setText(kal.format(skrg));
            
    }
    
    public void SetJam(){
        ActionListener taskPerformer = new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent evt) {
                Date dt = new Date();
                int n_jam = dt.getHours();
                int n_menit = dt.getMinutes();
                int n_detik = dt.getSeconds();
                if (n_jam <= 9){
                    nol_jam = "0";
                }
                if (n_menit <= 9){
                    nol_menit = "0";
                }
                if (n_detik <= 9){
                    nol_detik = "0";
                }
                
                String jam = nol_jam + Integer.toString(n_jam);
                String menit = nol_menit + Integer.toString(n_menit);
                String detik = nol_detik + Integer.toString(n_detik);
                Jam.setText(jam+" : "+menit+" : "+detik);
            }
            
        };
        new Timer(100, taskPerformer).start();
        
    }

}
