/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticketgb;

import java.text.MessageFormat;
import javax.swing.JTable;


/**
 *
 * @author Ryan
 */
public class tiket extends javax.swing.JFrame {

    /**
     * Creates new form tiket
     */
    public tiket(String nama,String jenkel,String telp,String tgl1,String jam1) {
        initComponents();
        tiketnamaptg.setText(nama);
        tiketnama1.setText(nama);
        tiketjk.setText(jenkel);
        tikettelp.setText(telp);
        tikettgl.setText(tgl1);
        tiketjam.setText(jam1);
        tikettgl1.setText(tgl1);
        tiketjam1.setText(jam1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        print = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tikettelp = new javax.swing.JLabel();
        tiketjk = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tiketnama1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tiketnamaptg = new javax.swing.JLabel();
        tikettgl = new javax.swing.JLabel();
        tiketjam = new javax.swing.JLabel();
        tikettgl1 = new javax.swing.JLabel();
        tiketjam1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));

        jButton3.setText("UBAH");
        jPanel3.add(jButton3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        print.setBackground(new java.awt.Color(204, 204, 204));
        print.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("085 755 875 127");
        print.add(jLabel14);
        jLabel14.setBounds(350, 220, 110, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Kontak Kami ");
        print.add(jLabel6);
        jLabel6.setBounds(230, 220, 80, 14);

        jLabel10.setText(":");
        print.add(jLabel10);
        jLabel10.setBounds(320, 220, 4, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("No. Telp ");
        print.add(jLabel5);
        jLabel5.setBounds(230, 190, 60, 14);

        jLabel9.setText(":");
        print.add(jLabel9);
        jLabel9.setBounds(320, 190, 4, 14);

        tikettelp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tikettelp.setText("Kosong");
        print.add(tikettelp);
        tikettelp.setBounds(350, 190, 180, 14);

        tiketjk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tiketjk.setText("Kosong");
        tiketjk.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        print.add(tiketjk);
        tiketjk.setBounds(350, 160, 180, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Jenis Kelamin ");
        print.add(jLabel4);
        jLabel4.setBounds(230, 160, 80, 14);

        jLabel8.setText(":");
        print.add(jLabel8);
        jLabel8.setBounds(320, 160, 4, 14);

        jLabel7.setText(":");
        print.add(jLabel7);
        jLabel7.setBounds(320, 130, 4, 14);

        tiketnama1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tiketnama1.setText("Kosong");
        print.add(tiketnama1);
        tiketnama1.setBounds(350, 130, 180, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nama ");
        print.add(jLabel2);
        jLabel2.setBounds(230, 130, 40, 14);

        tiketnamaptg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tiketnamaptg.setText("Kosong");
        print.add(tiketnamaptg);
        tiketnamaptg.setBounds(10, 120, 170, 15);

        tikettgl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tikettgl.setText("jLabel11");
        print.add(tikettgl);
        tikettgl.setBounds(430, 20, 130, 30);

        tiketjam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tiketjam.setText("jLabel12");
        print.add(tiketjam);
        tiketjam.setBounds(430, 50, 140, 15);

        tikettgl1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tikettgl1.setText("jLabel11");
        print.add(tikettgl1);
        tikettgl1.setBounds(10, 140, 130, 30);

        tiketjam1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tiketjam1.setText("jLabel12");
        print.add(tiketjam1);
        tiketjam1.setBounds(10, 180, 140, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Rp. 7000");
        print.add(jLabel3);
        jLabel3.setBounds(230, 250, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticketgb/tiket - Copy.jpg"))); // NOI18N
        print.add(jLabel1);
        jLabel1.setBounds(0, 0, 590, 300);

        getContentPane().add(print);
        print.setBounds(0, 0, 590, 300);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticketgb/large.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(440, 50, 300, 160);

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(600, 210, 130, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("<--- Gambar Tiket");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(600, 0, 130, 40);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(590, 280, 150, 20);

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(590, 0, 150, 40);

        setSize(new java.awt.Dimension(757, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    new main().show();
    this.dispose();  
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tiket(null,null,null,null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel print;
    private javax.swing.JLabel tiketjam;
    private javax.swing.JLabel tiketjam1;
    private javax.swing.JLabel tiketjk;
    private javax.swing.JLabel tiketnama1;
    private javax.swing.JLabel tiketnamaptg;
    private javax.swing.JLabel tikettelp;
    private javax.swing.JLabel tikettgl;
    private javax.swing.JLabel tikettgl1;
    // End of variables declaration//GEN-END:variables
}
